### ISSUE TITLE
Build failed on iOS simulator

### ISSUE THREAD

**Issue by skyline75489** [clowwindy/iOS-Python-Project#1]
Xcode 6.1.1. When running "Refresh Python Source"

```plaintext
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

**Comment by clowwindy** [comment]
symlink tornado with tornado package path or remove the symlink and remove related code in the app.
https://github.com/clowwindy/iOS-Python-Project/tree/master/app_packages

**Comment by clowwindy** [comment]
I replaced the symlink with real files in latest master.
